In [25]:
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [26]:
size = 128
dir='/home/samar/Desktop/project2/covid/Covid19-dataset/train'
train_data=tf.keras.utils.image_dataset_from_directory(directory=dir,
                                                        labels='inferred',
                                                        batch_size=251,
                                                        image_size=(size, size))

Found 251 files belonging to 3 classes.


In [27]:
xtrain, ytrain = next(iter(train_data))

In [28]:
ytrain

<tf.Tensor: shape=(251,), dtype=int32, numpy=
array([1, 1, 0, 0, 2, 1, 2, 1, 0, 0, 1, 2, 0, 0, 1, 0, 1, 0, 2, 0, 0, 1,
       0, 1, 1, 2, 0, 0, 0, 0, 0, 0, 1, 2, 2, 1, 1, 0, 2, 0, 0, 1, 0, 2,
       2, 0, 0, 1, 2, 2, 1, 1, 0, 1, 0, 2, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 2, 0, 1, 1, 2, 1, 2, 0, 1, 0, 2, 0, 0, 2, 0, 0, 0, 1, 0, 0,
       2, 1, 0, 1, 1, 2, 2, 2, 0, 2, 2, 0, 0, 0, 2, 0, 0, 0, 2, 1, 0, 0,
       0, 0, 1, 2, 0, 0, 2, 1, 0, 1, 2, 1, 0, 2, 0, 0, 1, 1, 2, 1, 2, 0,
       0, 0, 0, 1, 1, 1, 2, 0, 0, 2, 1, 1, 1, 2, 0, 0, 2, 0, 0, 1, 0, 0,
       2, 2, 0, 1, 0, 0, 1, 0, 1, 1, 2, 1, 0, 2, 0, 2, 2, 0, 0, 2, 2, 0,
       2, 2, 2, 2, 2, 2, 2, 0, 0, 1, 1, 2, 1, 0, 0, 2, 1, 2, 2, 1, 2, 0,
       0, 1, 1, 0, 0, 0, 2, 1, 2, 0, 2, 0, 0, 1, 1, 2, 1, 2, 0, 2, 0, 0,
       0, 1, 0, 0, 0, 2, 2, 1, 1, 2, 0, 1, 0, 2, 0, 1, 0, 2, 2, 2, 0, 0,
       0, 0, 2, 1, 1, 1, 0, 0, 1], dtype=int32)>

In [29]:
num_classes = 3

model = tf.keras.Sequential([
  tf.keras.layers.Rescaling(1./255, input_shape=(size, size, 3)),
  tf.keras.layers.Conv2D(16, 3, padding='same', activation='relu'),
  tf.keras.layers.MaxPooling2D(),
  tf.keras.layers.Conv2D(32, 3, padding='same', activation='relu'),
  tf.keras.layers.MaxPooling2D(),
  tf.keras.layers.Conv2D(64, 3, padding='same', activation='relu'),
  tf.keras.layers.MaxPooling2D(),
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dense(num_classes)
])

model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

epochs=30
history = model.fit(
  train_data,
  epochs=epochs
)

Epoch 1/30
1/1 [==============================] - 2s 2s/step - loss: 1.1127 - accuracy: 0.2789
Epoch 2/30
1/1 [==============================] - 2s 2s/step - loss: 1.3331 - accuracy: 0.4422
Epoch 3/30
1/1 [==============================] - 2s 2s/step - loss: 1.0193 - accuracy: 0.3267
Epoch 4/30
1/1 [==============================] - 2s 2s/step - loss: 1.0126 - accuracy: 0.4701
Epoch 5/30
1/1 [==============================] - 2s 2s/step - loss: 0.9833 - accuracy: 0.3825
Epoch 6/30
1/1 [==============================] - 2s 2s/step - loss: 0.9151 - accuracy: 0.4542
Epoch 7/30
1/1 [==============================] - 2s 2s/step - loss: 0.8374 - accuracy: 0.8845
Epoch 8/30
1/1 [==============================] - 2s 2s/step - loss: 0.7650 - accuracy: 0.8765
Epoch 9/30
1/1 [==============================] - 2s 2s/step - loss: 0.6890 - accuracy: 0.7888
Epoch 10/30
1/1 [==============================] - 2s 2s/step - loss: 0.6034 - accuracy: 0.8127
Epoch 11/30
1/1 [==============================] 

In [30]:
size = 128
dir='/home/samar/Desktop/project2/covid/Covid19-dataset/test'
test_data=tf.keras.utils.image_dataset_from_directory(directory=dir,
                                                        labels='inferred',
                                                        batch_size=66,
                                                        image_size=(size, size))

Found 66 files belonging to 3 classes.


In [31]:
xtest, ytest = next(iter(test_data))

In [32]:
y_predict = np.argmax(model.predict(xtest), axis=-1)

In [33]:
y_predict

array([0, 1, 1, 0, 1, 2, 1, 1, 0, 1, 1, 0, 1, 1, 0, 2, 2, 0, 2, 0, 1, 1,
       1, 1, 2, 0, 0, 2, 0, 2, 2, 0, 1, 1, 0, 0, 1, 1, 1, 2, 0, 0, 2, 2,
       1, 2, 1, 0, 0, 0, 0, 0, 2, 1, 0, 2, 2, 2, 0, 2, 0, 1, 0, 0, 0, 0])

In [34]:
ytest

<tf.Tensor: shape=(66,), dtype=int32, numpy=
array([0, 2, 1, 0, 1, 2, 2, 1, 0, 1, 1, 0, 1, 1, 0, 2, 2, 0, 2, 0, 1, 1,
       1, 1, 2, 0, 0, 2, 0, 1, 2, 0, 1, 2, 0, 0, 1, 1, 1, 2, 0, 0, 2, 2,
       1, 2, 1, 0, 0, 0, 0, 0, 2, 1, 0, 2, 2, 2, 0, 2, 0, 1, 0, 2, 0, 0],
      dtype=int32)>

In [35]:
a = []
for i,j in zip(ytest, y_predict):
    if(i==j):
        a.append(1)
    else: a.append(0)   

In [36]:
a = np.array(a)
np.unique(a, return_counts=True)

(array([0, 1]), array([ 5, 61]))

In [37]:
model.save('/home/samar/model.h5')